name: Continuous Integration

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:

  test-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn lint
        run: |
          yarn
          yarn lint
        env:
          CI: true
